export enum HandshakingServerbound {
    Handshake = 0x00,
    LegacyServerListPing = 0xFE
}

export enum StatusClientbound {
    Response = 0x00,
    Pong = 0x01
}

export enum StatusServerbound {
    Request = 0x00,
    Ping = 0x01
}

export enum LoginClientbound {
    Disconnect = 0x00,
    EncryptionRequest = 0x01,
    LoginSuccess = 0x02,
    SetCompression = 0x03,
    LoginPluginRequest = 0x04
}

export enum LoginServerbound {
    LoginStart = 0x00,
    EncryptionResponse = 0x01,
    LoginPluginResponse = 0x02
}

export enum PlayClientbound {
    SpawnEntity = 0x00,
    SpawnExperienceOrb = 0x01,
    SpawnLivingEntity = 0x02,
    SpawnPainting = 0x03,
    SpawnPlayer = 0x04,
    EntityAnimation = 0x05,
    Statistics = 0x06,
    AcknowledgePlayerDigging = 0x07,
    BlockBreakAnimation = 0x08,
    BlockEntityData = 0x09,
    BlockAction = 0x0A,
    BlockChange = 0x0B,
    BossBar = 0x0C,
    ServerDifficulty = 0x0D,
    ChatMessage = 0x0E,
    TabComplete = 0x0F,
    DeclareCommands = 0x10,
    WindowConfirmation = 0x11,
    CloseWindow = 0x12,
    WindowItems = 0x13,
    WindowProperty = 0x14,
    SetSlot = 0x15,
    SetCooldown = 0x16,
    PluginMessage = 0x17,
    NamedSoundEffect = 0x18,
    Disconnect = 0x19,
    EntityStatus = 0x1A,
    Explosion = 0x1B,
    UnloadChunk = 0x1C,
    ChangeGameState = 0x1D,
    OpenHorseWindow = 0x1E,
    KeepAlive = 0x1F,
    ChunkData = 0x20,
    Effect = 0x21,
    Particle = 0x22,
    UpdateLight = 0x23,
    JoinGame = 0x24,
    MapData = 0x25,
    TradeList = 0x26,
    EntityPosition = 0x27,
    EntityPositionandRotation = 0x28,
    EntityRotation = 0x29,
    EntityMovement = 0x2A,
    VehicleMove = 0x2B,
    OpenBook = 0x2C,
    OpenWindow = 0x2D,
    OpenSignEditor = 0x2E,
    CraftRecipeResponse = 0x2F,
    PlayerAbilities = 0x30,
    CombatEvent = 0x31,
    PlayerInfo = 0x32,
    FacePlayer = 0x33,
    PlayerPositionAndLook = 0x34,
    UnlockRecipes = 0x35,
    DestroyEntities = 0x36,
    RemoveEntityEffect = 0x37,
    ResourcePackSend = 0x38,
    Respawn = 0x39,
    EntityHeadLook = 0x3A,
    MultiBlockChange = 0x3B,
    SelectAdvancementTab = 0x3C,
    WorldBorder = 0x3D,
    Camera = 0x3E,
    HeldItemChange = 0x3F,
    UpdateViewPosition = 0x40,
    UpdateViewDistance = 0x41,
    SpawnPosition = 0x42,
    DisplayScoreboard = 0x43,
    EntityMetadata = 0x44,
    AttachEntity = 0x45,
    EntityVelocity = 0x46,
    EntityEquipment = 0x47,
    SetExperience = 0x48,
    UpdateHealth = 0x49,
    ScoreboardObjective = 0x4A,
    SetPassengers = 0x4B,
    Teams = 0x4C,
    UpdateScore = 0x4D,
    TimeUpdate = 0x4E,
    Title = 0x4F,
    EntitySoundEffect = 0x50,
    SoundEffect = 0x51,
    StopSound = 0x52,
    PlayerListHeaderAndFooter = 0x53,
    NBTQueryResponse = 0x54,
    CollectItem = 0x55,
    EntityTeleport = 0x56,
    Advancements = 0x57,
    EntityProperties = 0x58,
    EntityEffect = 0x59,
    DeclareRecipes = 0x5A,
    Tags = 0x5B    
}

export enum PlayServerbound {
    TeleportConfirm = 0x00,
    QueryBlockNBT = 0x01,
    QueryEntityNBT = 0x0D,
    SetDifficulty = 0x02,
    ChatMessage = 0x03,
    ClientStatus = 0x04,
    ClientSettings = 0x05,
    TabComplete = 0x06,
    WindowConfirmation = 0x07,
    ClickWindowButton = 0x08,
    ClickWindow = 0x09,
    CloseWindow = 0x0A,
    PluginMessage = 0x0B,
    EditBook = 0x0C,
    InteractEntity = 0x0E,
    GenerateStructure = 0x0F,
    KeepAlive = 0x10,
    LockDifficulty = 0x11,
    PlayerPosition = 0x12,
    PlayerPositionAndRotation = 0x13,
    PlayerRotation = 0x14,
    PlayerMovement = 0x15,
    VehicleMove = 0x16,
    SteerBoat = 0x17,
    PickItem = 0x18,
    CraftRecipeRequest = 0x19,
    PlayerAbilities = 0x1A,
    PlayerDigging = 0x1B,
    EntityAction = 0x1C,
    SteerVehicle = 0x1D,
    SetRecipeBookState = 0x1E,
    SetDisplayedRecipe = 0x1F,
    NameItem = 0x20,
    ResourcePackStatus = 0x21,
    AdvancementTab = 0x22,
    SelectTrade = 0x23,
    SetBeaconEffect = 0x24,
    HeldItemChange = 0x25,
    UpdateCommandBlock = 0x26,
    UpdateCommandBlockMinecart = 0x27,
    CreativeInventoryAction = 0x28,
    UpdateJigsawBlock = 0x29,
    UpdateStructureBlock = 0x2A,
    UpdateSign = 0x2B,
    Animation = 0x2C,
    Spectate = 0x2D,
    PlayerBlockPlacement = 0x2E,
    UseItem = 0x2F
}