name: 🛠 Build
on: [push, fork]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "lts/*"
            - run: npm install -g npm@latest
            - run: npm install
            - run: npm run build
