export default {
    'minecraft:chat_type': {
        type: 'minecraft:chat_type',
        value: [
            {
                name: 'minecraft:chat',
                id: 0,
                element: {
                    chat: { translation_key: 'chat.type.text', parameters: ['sender', 'content'] },
                    narration: { translation_key: 'chat.type.text.narrate', parameters: ['sender', 'content'] },
                },
            },
            {
                name: 'minecraft:say_command',
                id: 1,
                element: {
                    chat: { translation_key: 'chat.type.announcement', parameters: ['sender', 'content'] },
                    narration: { translation_key: 'chat.type.text.narrate', parameters: ['sender', 'content'] },
                },
            },
            {
                name: 'minecraft:msg_command_incoming',
                id: 2,
                element: {
                    chat: { translation_key: 'commands.message.display.incoming', style: { color: 'gray', italic: '1b' }, parameters: ['sender', 'content'] },
                    narration: { translation_key: 'chat.type.text.narrate', parameters: ['sender', 'content'] },
                },
            },
            {
                name: 'minecraft:msg_command_outgoing',
                id: 3,
                element: {
                    chat: { translation_key: 'commands.message.display.outgoing', style: { color: 'gray', italic: '1b' }, parameters: ['target', 'content'] },
                    narration: { translation_key: 'chat.type.text.narrate', parameters: ['sender', 'content'] },
                },
            },
            {
                name: 'minecraft:team_msg_command_incoming',
                id: 4,
                element: {
                    chat: { translation_key: 'chat.type.team.text', parameters: ['target', 'sender', 'content'] },
                    narration: { translation_key: 'chat.type.text.narrate', parameters: ['sender', 'content'] },
                },
            },
            {
                name: 'minecraft:team_msg_command_outgoing',
                id: 5,
                element: {
                    chat: { translation_key: 'chat.type.team.sent', parameters: ['target', 'sender', 'content'] },
                    narration: { translation_key: 'chat.type.text.narrate', parameters: ['sender', 'content'] },
                },
            },
            {
                name: 'minecraft:emote_command',
                id: 6,
                element: {
                    chat: { translation_key: 'chat.type.emote', parameters: ['sender', 'content'] },
                    narration: { translation_key: 'chat.type.emote', parameters: ['sender', 'content'] },
                },
            },
        ],
    },
    'minecraft:dimension_type': {
        type: 'minecraft:dimension_type',
        value: [
            {
                name: 'minecraft:overworld',
                id: 0,
                element: {
                    piglin_safe: '0b',
                    natural: '1b',
                    ambient_light: '0f',
                    monster_spawn_block_light_limit: 0,
                    infiniburn: '#minecraft:infiniburn_overworld',
                    respawn_anchor_works: '0b',
                    has_skylight: '1b',
                    bed_works: '1b',
                    effects: 'minecraft:overworld',
                    has_raids: '1b',
                    logical_height: 384,
                    coordinate_scale: '1d',
                    monster_spawn_light_level: { type: 'minecraft:uniform', value: { min_inclusive: 0, max_inclusive: 7 } },
                    min_y: -64,
                    ultrawarm: '0b',
                    has_ceiling: '0b',
                    height: 384,
                },
            },
            {
                name: 'minecraft:the_nether',
                id: 1,
                element: {
                    piglin_safe: '1b',
                    natural: '0b',
                    ambient_light: '0.10000000149011612f',
                    monster_spawn_block_light_limit: 15,
                    infiniburn: '#minecraft:infiniburn_nether',
                    respawn_anchor_works: '1b',
                    has_skylight: '0b',
                    bed_works: '0b',
                    effects: 'minecraft:the_nether',
                    fixed_time: '18000l',
                    has_raids: '0b',
                    logical_height: 128,
                    coordinate_scale: '8d',
                    monster_spawn_light_level: 11,
                    min_y: 0,
                    ultrawarm: '1b',
                    has_ceiling: '1b',
                    height: 256,
                },
            },
            {
                name: 'minecraft:the_end',
                id: 2,
                element: {
                    piglin_safe: '0b',
                    natural: '0b',
                    ambient_light: '0f',
                    monster_spawn_block_light_limit: 0,
                    infiniburn: '#minecraft:infiniburn_end',
                    respawn_anchor_works: '0b',
                    has_skylight: '0b',
                    bed_works: '0b',
                    effects: 'minecraft:the_end',
                    fixed_time: '6000l',
                    has_raids: '1b',
                    logical_height: 256,
                    coordinate_scale: '1d',
                    monster_spawn_light_level: { type: 'minecraft:uniform', value: { min_inclusive: 0, max_inclusive: 7 } },
                    min_y: 0,
                    ultrawarm: '0b',
                    has_ceiling: '0b',
                    height: 256,
                },
            },
            {
                name: 'minecraft:overworld_caves',
                id: 3,
                element: {
                    piglin_safe: '0b',
                    natural: '1b',
                    ambient_light: '0f',
                    monster_spawn_block_light_limit: 0,
                    infiniburn: '#minecraft:infiniburn_overworld',
                    respawn_anchor_works: '0b',
                    has_skylight: '1b',
                    bed_works: '1b',
                    effects: 'minecraft:overworld',
                    has_raids: '1b',
                    logical_height: 384,
                    coordinate_scale: '1d',
                    monster_spawn_light_level: { type: 'minecraft:uniform', value: { min_inclusive: 0, max_inclusive: 7 } },
                    min_y: -64,
                    ultrawarm: '0b',
                    has_ceiling: '1b',
                    height: 384,
                },
            },
        ],
    },
    'minecraft:worldgen/biome': {
        type: 'minecraft:worldgen/biome',
        value: [
            {
                name: 'minecraft:the_void',
                id: 0,
                element: {
                    precipitation: 'none',
                    effects: {
                        sky_color: 8103167,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:plains',
                id: 1,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 7907327,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.800000011920929f',
                    downfall: '0.4000000059604645f',
                },
            },
            {
                name: 'minecraft:sunflower_plains',
                id: 2,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 7907327,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.800000011920929f',
                    downfall: '0.4000000059604645f',
                },
            },
            {
                name: 'minecraft:snowy_plains',
                id: 3,
                element: {
                    precipitation: 'snow',
                    effects: {
                        sky_color: 8364543,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:ice_spikes',
                id: 4,
                element: {
                    precipitation: 'snow',
                    effects: {
                        sky_color: 8364543,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:desert',
                id: 5,
                element: {
                    precipitation: 'none',
                    effects: {
                        sky_color: 7254527,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '2f',
                    downfall: '0f',
                },
            },
            {
                name: 'minecraft:swamp',
                id: 6,
                element: {
                    precipitation: 'rain',
                    effects: {
                        grass_color_modifier: 'swamp',
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.swamp', min_delay: 12000 },
                        sky_color: 7907327,
                        foliage_color: 6975545,
                        water_fog_color: 2302743,
                        fog_color: 12638463,
                        water_color: 6388580,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.800000011920929f',
                    downfall: '0.8999999761581421f',
                },
            },
            {
                name: 'minecraft:mangrove_swamp',
                id: 7,
                element: {
                    precipitation: 'rain',
                    effects: {
                        grass_color_modifier: 'swamp',
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.swamp', min_delay: 12000 },
                        sky_color: 7907327,
                        foliage_color: 9285927,
                        water_fog_color: 5077600,
                        fog_color: 12638463,
                        water_color: 3832426,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.800000011920929f',
                    downfall: '0.8999999761581421f',
                },
            },
            {
                name: 'minecraft:forest',
                id: 8,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.jungle_and_forest', min_delay: 12000 },
                        sky_color: 7972607,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.699999988079071f',
                    downfall: '0.800000011920929f',
                },
            },
            {
                name: 'minecraft:flower_forest',
                id: 9,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.jungle_and_forest', min_delay: 12000 },
                        sky_color: 7972607,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.699999988079071f',
                    downfall: '0.800000011920929f',
                },
            },
            {
                name: 'minecraft:birch_forest',
                id: 10,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.jungle_and_forest', min_delay: 12000 },
                        sky_color: 8037887,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.6000000238418579f',
                    downfall: '0.6000000238418579f',
                },
            },
            {
                name: 'minecraft:dark_forest',
                id: 11,
                element: {
                    precipitation: 'rain',
                    effects: {
                        grass_color_modifier: 'dark_forest',
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.jungle_and_forest', min_delay: 12000 },
                        sky_color: 7972607,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.699999988079071f',
                    downfall: '0.800000011920929f',
                },
            },
            {
                name: 'minecraft:old_growth_birch_forest',
                id: 12,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.jungle_and_forest', min_delay: 12000 },
                        sky_color: 8037887,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.6000000238418579f',
                    downfall: '0.6000000238418579f',
                },
            },
            {
                name: 'minecraft:old_growth_pine_taiga',
                id: 13,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.old_growth_taiga', min_delay: 12000 },
                        sky_color: 8168447,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.30000001192092896f',
                    downfall: '0.800000011920929f',
                },
            },
            {
                name: 'minecraft:old_growth_spruce_taiga',
                id: 14,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.old_growth_taiga', min_delay: 12000 },
                        sky_color: 8233983,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.25f',
                    downfall: '0.800000011920929f',
                },
            },
            {
                name: 'minecraft:taiga',
                id: 15,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8233983,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.25f',
                    downfall: '0.800000011920929f',
                },
            },
            {
                name: 'minecraft:snowy_taiga',
                id: 16,
                element: {
                    precipitation: 'snow',
                    effects: {
                        sky_color: 8625919,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4020182,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '-0.5f',
                    downfall: '0.4000000059604645f',
                },
            },
            {
                name: 'minecraft:savanna',
                id: 17,
                element: {
                    precipitation: 'none',
                    effects: {
                        sky_color: 7254527,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '2f',
                    downfall: '0f',
                },
            },
            {
                name: 'minecraft:savanna_plateau',
                id: 18,
                element: {
                    precipitation: 'none',
                    effects: {
                        sky_color: 7254527,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '2f',
                    downfall: '0f',
                },
            },
            {
                name: 'minecraft:windswept_hills',
                id: 19,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8233727,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.20000000298023224f',
                    downfall: '0.30000001192092896f',
                },
            },
            {
                name: 'minecraft:windswept_gravelly_hills',
                id: 20,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8233727,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.20000000298023224f',
                    downfall: '0.30000001192092896f',
                },
            },
            {
                name: 'minecraft:windswept_forest',
                id: 21,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8233727,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.20000000298023224f',
                    downfall: '0.30000001192092896f',
                },
            },
            {
                name: 'minecraft:windswept_savanna',
                id: 22,
                element: {
                    precipitation: 'none',
                    effects: {
                        sky_color: 7254527,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '2f',
                    downfall: '0f',
                },
            },
            {
                name: 'minecraft:jungle',
                id: 23,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.jungle_and_forest', min_delay: 12000 },
                        sky_color: 7842047,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.949999988079071f',
                    downfall: '0.8999999761581421f',
                },
            },
            {
                name: 'minecraft:sparse_jungle',
                id: 24,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.jungle_and_forest', min_delay: 12000 },
                        sky_color: 7842047,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.949999988079071f',
                    downfall: '0.800000011920929f',
                },
            },
            {
                name: 'minecraft:bamboo_jungle',
                id: 25,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.jungle_and_forest', min_delay: 12000 },
                        sky_color: 7842047,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.949999988079071f',
                    downfall: '0.8999999761581421f',
                },
            },
            {
                name: 'minecraft:badlands',
                id: 26,
                element: {
                    precipitation: 'none',
                    effects: {
                        sky_color: 7254527,
                        grass_color: 9470285,
                        foliage_color: 10387789,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '2f',
                    downfall: '0f',
                },
            },
            {
                name: 'minecraft:eroded_badlands',
                id: 27,
                element: {
                    precipitation: 'none',
                    effects: {
                        sky_color: 7254527,
                        grass_color: 9470285,
                        foliage_color: 10387789,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '2f',
                    downfall: '0f',
                },
            },
            {
                name: 'minecraft:wooded_badlands',
                id: 28,
                element: {
                    precipitation: 'none',
                    effects: {
                        sky_color: 7254527,
                        grass_color: 9470285,
                        foliage_color: 10387789,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '2f',
                    downfall: '0f',
                },
            },
            {
                name: 'minecraft:meadow',
                id: 29,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.meadow', min_delay: 12000 },
                        sky_color: 8103167,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 937679,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.800000011920929f',
                },
            },
            {
                name: 'minecraft:grove',
                id: 30,
                element: {
                    precipitation: 'snow',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.grove', min_delay: 12000 },
                        sky_color: 8495359,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '-0.20000000298023224f',
                    downfall: '0.800000011920929f',
                },
            },
            {
                name: 'minecraft:snowy_slopes',
                id: 31,
                element: {
                    precipitation: 'snow',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.snowy_slopes', min_delay: 12000 },
                        sky_color: 8560639,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '-0.30000001192092896f',
                    downfall: '0.8999999761581421f',
                },
            },
            {
                name: 'minecraft:frozen_peaks',
                id: 32,
                element: {
                    precipitation: 'snow',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.frozen_peaks', min_delay: 12000 },
                        sky_color: 8756735,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '-0.699999988079071f',
                    downfall: '0.8999999761581421f',
                },
            },
            {
                name: 'minecraft:jagged_peaks',
                id: 33,
                element: {
                    precipitation: 'snow',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.jagged_peaks', min_delay: 12000 },
                        sky_color: 8756735,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '-0.699999988079071f',
                    downfall: '0.8999999761581421f',
                },
            },
            {
                name: 'minecraft:stony_peaks',
                id: 34,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.stony_peaks', min_delay: 12000 },
                        sky_color: 7776511,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '1f',
                    downfall: '0.30000001192092896f',
                },
            },
            {
                name: 'minecraft:river',
                id: 35,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8103167,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:frozen_river',
                id: 36,
                element: {
                    precipitation: 'snow',
                    effects: {
                        sky_color: 8364543,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 3750089,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:beach',
                id: 37,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 7907327,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.800000011920929f',
                    downfall: '0.4000000059604645f',
                },
            },
            {
                name: 'minecraft:snowy_beach',
                id: 38,
                element: {
                    precipitation: 'snow',
                    effects: {
                        sky_color: 8364543,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4020182,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.05000000074505806f',
                    downfall: '0.30000001192092896f',
                },
            },
            {
                name: 'minecraft:stony_shore',
                id: 39,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8233727,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.20000000298023224f',
                    downfall: '0.30000001192092896f',
                },
            },
            {
                name: 'minecraft:warm_ocean',
                id: 40,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8103167,
                        water_fog_color: 270131,
                        fog_color: 12638463,
                        water_color: 4445678,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:lukewarm_ocean',
                id: 41,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8103167,
                        water_fog_color: 267827,
                        fog_color: 12638463,
                        water_color: 4566514,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:deep_lukewarm_ocean',
                id: 42,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8103167,
                        water_fog_color: 267827,
                        fog_color: 12638463,
                        water_color: 4566514,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:ocean',
                id: 43,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8103167,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:deep_ocean',
                id: 44,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8103167,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:cold_ocean',
                id: 45,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8103167,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4020182,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:deep_cold_ocean',
                id: 46,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8103167,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4020182,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:frozen_ocean',
                id: 47,
                element: {
                    precipitation: 'snow',
                    effects: {
                        sky_color: 8364543,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 3750089,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0f',
                    downfall: '0.5f',
                    temperature_modifier: 'frozen',
                },
            },
            {
                name: 'minecraft:deep_frozen_ocean',
                id: 48,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 8103167,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 3750089,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                    temperature_modifier: 'frozen',
                },
            },
            {
                name: 'minecraft:mushroom_fields',
                id: 49,
                element: {
                    precipitation: 'rain',
                    effects: {
                        sky_color: 7842047,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.8999999761581421f',
                    downfall: '1f',
                },
            },
            {
                name: 'minecraft:dripstone_caves',
                id: 50,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.dripstone_caves', min_delay: 12000 },
                        sky_color: 7907327,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.800000011920929f',
                    downfall: '0.4000000059604645f',
                },
            },
            {
                name: 'minecraft:lush_caves',
                id: 51,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.lush_caves', min_delay: 12000 },
                        sky_color: 8103167,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:deep_dark',
                id: 52,
                element: {
                    precipitation: 'rain',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.overworld.deep_dark', min_delay: 12000 },
                        sky_color: 7907327,
                        water_fog_color: 329011,
                        fog_color: 12638463,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.800000011920929f',
                    downfall: '0.4000000059604645f',
                },
            },
            {
                name: 'minecraft:nether_wastes',
                id: 53,
                element: {
                    precipitation: 'none',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.nether.nether_wastes', min_delay: 12000 },
                        sky_color: 7254527,
                        ambient_sound: 'minecraft:ambient.nether_wastes.loop',
                        additions_sound: { sound: 'minecraft:ambient.nether_wastes.additions', tick_chance: '0.0111d' },
                        water_fog_color: 329011,
                        fog_color: 3344392,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.nether_wastes.mood', block_search_extent: 8 },
                    },
                    temperature: '2f',
                    downfall: '0f',
                },
            },
            {
                name: 'minecraft:warped_forest',
                id: 54,
                element: {
                    precipitation: 'none',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.nether.warped_forest', min_delay: 12000 },
                        sky_color: 7254527,
                        ambient_sound: 'minecraft:ambient.warped_forest.loop',
                        additions_sound: { sound: 'minecraft:ambient.warped_forest.additions', tick_chance: '0.0111d' },
                        particle: { probability: '0.014279999770224094f', options: { type: 'minecraft:warped_spore' } },
                        water_fog_color: 329011,
                        fog_color: 1705242,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.warped_forest.mood', block_search_extent: 8 },
                    },
                    temperature: '2f',
                    downfall: '0f',
                },
            },
            {
                name: 'minecraft:crimson_forest',
                id: 55,
                element: {
                    precipitation: 'none',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.nether.crimson_forest', min_delay: 12000 },
                        sky_color: 7254527,
                        ambient_sound: 'minecraft:ambient.crimson_forest.loop',
                        additions_sound: { sound: 'minecraft:ambient.crimson_forest.additions', tick_chance: '0.0111d' },
                        particle: { probability: '0.02500000037252903f', options: { type: 'minecraft:crimson_spore' } },
                        water_fog_color: 329011,
                        fog_color: 3343107,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.crimson_forest.mood', block_search_extent: 8 },
                    },
                    temperature: '2f',
                    downfall: '0f',
                },
            },
            {
                name: 'minecraft:soul_sand_valley',
                id: 56,
                element: {
                    precipitation: 'none',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.nether.soul_sand_valley', min_delay: 12000 },
                        sky_color: 7254527,
                        ambient_sound: 'minecraft:ambient.soul_sand_valley.loop',
                        additions_sound: { sound: 'minecraft:ambient.soul_sand_valley.additions', tick_chance: '0.0111d' },
                        particle: { probability: '0.0062500000931322575f', options: { type: 'minecraft:ash' } },
                        water_fog_color: 329011,
                        fog_color: 1787717,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.soul_sand_valley.mood', block_search_extent: 8 },
                    },
                    temperature: '2f',
                    downfall: '0f',
                },
            },
            {
                name: 'minecraft:basalt_deltas',
                id: 57,
                element: {
                    precipitation: 'none',
                    effects: {
                        music: { replace_current_music: '0b', max_delay: 24000, sound: 'minecraft:music.nether.basalt_deltas', min_delay: 12000 },
                        sky_color: 7254527,
                        ambient_sound: 'minecraft:ambient.basalt_deltas.loop',
                        additions_sound: { sound: 'minecraft:ambient.basalt_deltas.additions', tick_chance: '0.0111d' },
                        particle: { probability: '0.1180933341383934f', options: { type: 'minecraft:white_ash' } },
                        water_fog_color: 329011,
                        fog_color: 6840176,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.basalt_deltas.mood', block_search_extent: 8 },
                    },
                    temperature: '2f',
                    downfall: '0f',
                },
            },
            {
                name: 'minecraft:the_end',
                id: 58,
                element: {
                    precipitation: 'none',
                    effects: {
                        sky_color: 0,
                        water_fog_color: 329011,
                        fog_color: 10518688,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:end_highlands',
                id: 59,
                element: {
                    precipitation: 'none',
                    effects: {
                        sky_color: 0,
                        water_fog_color: 329011,
                        fog_color: 10518688,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:end_midlands',
                id: 60,
                element: {
                    precipitation: 'none',
                    effects: {
                        sky_color: 0,
                        water_fog_color: 329011,
                        fog_color: 10518688,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:small_end_islands',
                id: 61,
                element: {
                    precipitation: 'none',
                    effects: {
                        sky_color: 0,
                        water_fog_color: 329011,
                        fog_color: 10518688,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
            {
                name: 'minecraft:end_barrens',
                id: 62,
                element: {
                    precipitation: 'none',
                    effects: {
                        sky_color: 0,
                        water_fog_color: 329011,
                        fog_color: 10518688,
                        water_color: 4159204,
                        mood_sound: { tick_delay: 6000, offset: '2d', sound: 'minecraft:ambient.cave', block_search_extent: 8 },
                    },
                    temperature: '0.5f',
                    downfall: '0.5f',
                },
            },
        ],
    },
};
